/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/customer/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Storico richieste auto sostitutiva del cliente */
        get: {
            parameters: {
                query?: {
                    /** @description Numero di pagina (0-based) */
                    page?: components["parameters"]["PageParam"];
                    /** @description Dimensione della pagina */
                    size?: components["parameters"]["SizeParam"];
                    /** @description Criterio di ordinamento (es. id,desc) */
                    sort?: components["parameters"]["SortParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista paginata delle richieste del cliente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomerRequestPage"];
                    };
                };
            };
        };
        put?: never;
        /** Crea una nuova richiesta di auto sostitutiva */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewCustomerRequest"];
                };
            };
            responses: {
                /** @description Richiesta creata con successo */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Dati non validi */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Errore del server */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operator/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statistiche globali per l'operatore */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description KPI della dashboard operatore */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OperatorStats"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operator/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista di tutte le richieste (vista operatore) */
        get: {
            parameters: {
                query?: {
                    /** @description Numero di pagina (0-based) */
                    page?: components["parameters"]["PageParam"];
                    /** @description Dimensione della pagina */
                    size?: components["parameters"]["SizeParam"];
                    /** @description Criterio di ordinamento (es. id,desc) */
                    sort?: components["parameters"]["SortParam"];
                    /** @description Filtro di ricerca testuale */
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista paginata delle richieste per l'operatore */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OperatorRequestPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operator/vehicles/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ricerca auto sostitutive disponibili */
        get: {
            parameters: {
                query: {
                    startDate: string;
                    endDate: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista delle auto disponibili */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AvailableCar"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operator/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prenota un'auto sostitutiva per un cliente */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewBooking"];
                };
            };
            responses: {
                /** @description Auto prenotata con successo */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Errore validazione */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Auto o Cliente non trovato */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CustomerRequestPage: {
            content?: components["schemas"]["CustomerRequest"][];
            totalElements?: number;
            totalPages?: number;
        };
        OperatorRequestPage: {
            content?: components["schemas"]["OperatorRequest"][];
            totalElements?: number;
            totalPages?: number;
        };
        CustomerRequest: {
            /** @description ID Univoco o Seriale della richiesta (es. 00001) */
            id?: string;
            plate?: string;
            vehicle?: string;
            /** @description Alimentazione (es. Diesel, Benzina) */
            fuel?: string;
            /** Format: date */
            deliveryDate?: string;
            /** Format: date */
            returnDate?: string;
            /** @enum {string} */
            status?: "In attesa" | "In consegna" | "Consegnata" | "Rifiutato";
        };
        OperatorRequest: components["schemas"]["CustomerRequest"] & {
            customerName?: string;
        };
        NewCustomerRequest: {
            /** @description Targa del veicolo da sostituire */
            replacedVehiclePlate: string;
            options?: components["schemas"]["RequestOptions"];
            /** @enum {string} */
            deliveryType: "POINT_OF_DELIVERY" | "HOME_DELIVERY";
            customerInfo: components["schemas"]["CustomerInfo"];
        };
        RequestOptions: {
            /** @enum {string} */
            gearbox?: "Automatico" | "Manuale";
            snowChains?: boolean;
            doubleKeys?: boolean;
            isofix?: boolean;
            /** @description Note libere (es. 'Necessito di un'auto con 7 posti...') */
            notes?: string;
        };
        CustomerInfo: {
            name?: string;
            phone?: string;
            email?: string;
            /** @description Indirizzo per la consegna a casa, se applicabile. */
            address?: string;
        };
        OperatorStats: {
            totalReplacedCars?: number;
            totalRequests?: number;
            /**
             * Format: float
             * @description Spese totali in Euro
             */
            totalExpenses?: number;
        };
        AvailableCar: {
            plate?: string;
            brand?: string;
            model?: string;
            /** @description Tipologia (es. City Car, Berlina) */
            type?: string;
            seats?: number;
            fuel?: string;
            gearbox?: string;
            /**
             * Format: float
             * @description Costo per il periodo selezionato
             */
            price?: number;
        };
        NewBooking: {
            customerEmail: string;
            replacedVehiclePlate: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            carPlate: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Numero di pagina (0-based) */
        PageParam: number;
        /** @description Dimensione della pagina */
        SizeParam: number;
        /** @description Criterio di ordinamento (es. id,desc) */
        SortParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
